version: '3'
services:
  zookeeper:
    image: parrotstream/zookeeper:latest
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    networks:
    - parrot
  hadoop:
    image: parrotstream/hadoop:3.0.3
    links:
    - zookeeper
    networks:
    - parrot
    ports:
    - 9870:9870
    - 9864:9864
    - 9820:9820
    - 8042:8042
    - 8088:8088
    - 8188:8188
    - 19888:19888
  hbase:
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/hbase:latest
    networks:
    - parrot
    links:
    - hadoop
    - zookeeper
    ports:
    - 8080:8080
    - 8085:8085
    - 9090:9090
    - 9095:9095
    - 60000:60000
    - 60010:60010
    - 60020:60020
    - 60030:60030
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge
