version: '3'
services:
  hbase:
    container_name: hbase
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/hbase:latest
    external_links:
    - hadoop
    - zookeeper
    ports:
    - 8080:8080
    - 8085:8085
    - 9090:9090
    - 9095:9095
    - 60000:60000
    - 60010:60010
    - 60020:60020
    - 60030:60030
networks:
  default:
    external:
      name: parrot_default
