version: "2"

services:

    zookeeper:
        extends:
            file: zookeeper.yml
            service: zookeeper

    hadoop:
        extends:
            file: hadoop.yml
            service: hadoop
        links:
            - zookeeper

    hbase:
        image: mcapitanio/hbase:latest
        networks:
            - hadoop
        volumes:
            - hbase_logs:/opt/hbase/logs
            - hbase_conf:/opt/hbase/conf
        volumes_from:
            - hadoop
        links:
            - hadoop
            - zookeeper
        ports:
            - "8080:8080"
            - "8085:8085"
            - "9090:9090"
            - "9095:9095"
            - "60000:60000"
            - "60010:60010"
            - "60020:60020"
            - "60030:60030"

volumes:
    hadoop_conf:
    hadoop_hdfs:
    hadoop_logs:
    hbase_conf:
    hbase_logs:
    zookeeper_conf:
    zookeeper_logs:
    zookeeper_data:

networks:
    hadoop:
        driver: bridge
